In [1]:
#Numpy
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [4]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
b[0][1]

2

In [14]:
zeros = np.zeros((3,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [15]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [21]:
#Randomly(linearly divided baseed ob count) give the numbers based on count between x and y (x,y,count)
np.linspace(10,20,30)

array([10.        , 10.34482759, 10.68965517, 11.03448276, 11.37931034,
       11.72413793, 12.06896552, 12.4137931 , 12.75862069, 13.10344828,
       13.44827586, 13.79310345, 14.13793103, 14.48275862, 14.82758621,
       15.17241379, 15.51724138, 15.86206897, 16.20689655, 16.55172414,
       16.89655172, 17.24137931, 17.5862069 , 17.93103448, 18.27586207,
       18.62068966, 18.96551724, 19.31034483, 19.65517241, 20.        ])

In [24]:
#even
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [25]:
#np.empty creates empty array with 2 elements

np.empty(2)

array([ 0., 10.])

In [26]:
arr = np.array([2,3,6,1,8,4,5,9])


In [28]:
np.random.rand(10)

array([0.75232891, 0.87960592, 0.05058506, 0.13646792, 0.51770065,
       0.07852266, 0.91753372, 0.81888862, 0.36763383, 0.30088697])

In [29]:
#fill matrices with same no
np.full((3,4),10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [34]:
np.random.random((2,4))

array([[0.43317367, 0.5326586 , 0.42817379, 0.57160712],
       [0.6305133 , 0.66859039, 0.54129165, 0.19153829]])

In [36]:
twodim = np.array([[1,2,3,4,5],[6,7,8,9,8]])
twodim

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 8]])

In [37]:
twodim.ndim

2

In [38]:
twodim.shape

(2, 5)

In [40]:
#Adding , Removing and sorting elementts
arr


array([2, 3, 6, 1, 8, 4, 5, 9])

In [41]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 8, 9])

In [43]:
i = np.array([3,4,5])
j = np.array([7,8,9])
np.concatenate((i,j))

array([3, 4, 5, 7, 8, 9])

In [47]:
np.concatenate((i,j),axis = 0)

array([3, 4, 5, 7, 8, 9])

In [50]:
arr.size

8

In [52]:
arr.reshape(2,4)

array([[2, 3, 6, 1],
       [8, 4, 5, 9]])

In [53]:
np.sum(arr)

38

In [54]:
np.max(arr)

9

In [55]:
np.min(arr)

1

In [56]:
np.mean(arr)

4.75

In [59]:
np.sum([[1,1],[2,2]],axis = 0)

array([3, 3])

In [60]:
np.sum([[1,1],[2,2]],axis=1)

array([2, 4])

In [62]:
np.sum([1,2,3])

6

In [64]:
np.subtract(4,5)

-1

In [66]:
np.divide(20,4)

5.0

In [67]:
np.multiply(2,4)

8

In [69]:
#Math
mathod = np.array([2,3,4])
print("Exponent : ", np.exp(a))
print("SquareRoot : ",np.sqrt(a))
print("Sin :", np.sin(a))
print("Cos :",np.cos(a))
print("Log : ",np.log(a))




Exponent :  [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
SquareRoot :  [1.         1.41421356 1.73205081 2.         2.23606798]
Sin : [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Cos : [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
Log :  [0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [71]:
#Array Comparison 
d=np.array([1,2,3,4])
e = np.array([9,8,7,4])
f = np.array([1,2,3,4])
print(np.equal(d,e))
print(np.equal(d,f))

[False False False  True]
[ True  True  True  True]


In [72]:
print(np.array_equal(d,e))
print(np.array_equal(d,f))


False
True


In [78]:
operation = np.array([1,2,33,45,5,5,6])
print("Sum :", np.sum(a))
print("Minumum :", np.min(a))
print("Maximum : ", np.min(a))
print("Mean :", np.mean(a))
print("Median :", np.median(a))
print("Correlation Coefficient:", np.corrcoef(a))
print("Standard deviation  : ",np.std(a))

Sum : 15
Minumum : 1
Maximum :  1
Mean : 3.0
Median : 3.0
Correlation Coefficient: 1.0
Standard deviation  :  1.4142135623730951


In [80]:
n = np.array([1,2,3,21,30])
np.mean(n)   #average
np.median(n)   #median means middle element


3.0

In [84]:
#concept of broadcasting
a1= np.array([[1,1,2],[3,4,5],[4,4,6],[2,4,3]])
b1=np.array([1,2,3])
print("A :\n",a)
print("b :\n",b)


A :
 [[1 1 2]
 [3 4 5]
 [4 4 6]
 [2 4 3]]
b :
 [1 2 3]


In [85]:
a1+b1
#here if we notic b is converted into 4x3 array and addition occured


array([[2, 3, 5],
       [4, 6, 8],
       [5, 6, 9],
       [3, 6, 6]])

In [86]:
a


array([[1, 1, 2],
       [3, 4, 5],
       [4, 4, 6],
       [2, 4, 3]])

In [87]:
a[1]

array([3, 4, 5])

In [88]:
a[1:3]

array([[3, 4, 5],
       [4, 4, 6]])

In [92]:
a[0:4,:1]

array([[1],
       [3],
       [4],
       [2]])

In [94]:
# Numpy vs List
#BY memory

import sys
#list 
listt=range(1000)
print("Size of List : ",sys.getsizeof(1)*len(listt))

#numpyarray
arr = np.arange(1000)
print("Size of Array : ",a.size*a.itemsize)

Size of List :  14000
Size of Array :  48


In [98]:
#Speed wise
import time
size = 1000000  
#List
list1 = range(size)
list2 = range(size)
   
#arrays
array1 = np.arange(size)  
array2 = np.arange(size)
   
#before time
initialTime = time.time()
  
# multiplying  elements of both the lists and stored in another list
resultantList = [(a * b) for a, b in zip(list1, list2)]
   
# calculating execution time
print("Time taken by List : ",(time.time() - initialTime))
   
# Before time
initialTime = time.time()
  
#after time
resultantArray = array1 * array2
   
# calculating execution time 
print("Time taken by NumPy :",(time.time() - initialTime))


Time taken by List :  1.1325721740722656
Time taken by NumPy : 0.017009735107421875
